import streamlit as st
import os
import pandas as pd
from fpdf import FPDF
from dotenv import load_dotenv

load_dotenv()
import db_utils
import storage_utils
import grader_engine

st.set_page_config(page_title="Eskwela", layout="wide")

# --- CUSTOM CSS ---
st.markdown("""
<style>
    .stApp {background-color: #12002F;}
    .stTabs [data-baseweb="tab-list"] {
        gap: 24px; background-color: transparent; padding-bottom: 10px; border-bottom: 3px solid #38BDF8;
    }
    .stTabs [data-baseweb="tab"] {
        height: auto; white-space: pre-wrap; background-color: transparent !important;
        border-radius: 0px; border: none; color: #FCA5A5; font-size: 16px; font-weight: 600; padding: 10px 0px;
    }
    .stTabs [aria-selected="true"] {
        background-color: transparent !important; color: #FFFFFF !important; border-bottom: 4px solid #FDE047;
    }
    .stTabs [data-baseweb="tab"]:hover {color: #FFFFFF;}
    .stProgress > div > div > div > div {
        background-color: #22C55E;
    }
    .howto-box {
        background-color: #1F1147;
        padding: 15px;
        border-radius: 10px;
        border-left: 6px solid #FDE047;
        margin-bottom: 20px;
        color: #E9D5FF;
        font-size: 14px;
    }
</style>

""", unsafe_allow_html=True)

st.title("Eskwela AI")
st.subheader("Automated Homework Grading Assistant")

# --- HOW TO USE GUIDE (NEW) ---
st.markdown("""
<div class="howto-box">
    <b> How to Use:</b><br>
    1. <b>Login:</b> Enter your Username in the configuration panel<br>
    2. <b>Upload:</b> Upload your Marking Scheme (PDF) and either single or multiple Student Answer Papers (PDF).<br>
    3. <b>Configure:</b> Set "Total Marks" (leave <b>0</b> to auto-detect from marking scheme) <br>
    4. <b>Upload</b> Click upload Custom Template, if you need to upload a custom report template (not essential) <br>
    5. <b>Run:</b> Click "Run Batch Grading" to process files and download your PDF reports.<br>
    6. <b>Limits:</b> Contact us if you need more tokens, for affordable upgrades 
</div>
</div>
""", unsafe_allow_html=True)

# --- HELPER: USER AUTH & QUOTA ---
def get_authorized_users():
    """Parses the .env string 'user:limit,user2:limit' into a dict."""
    raw_string = os.environ.get("TUTOR_QUOTAS", "")
    users = {}
    if raw_string:
        for entry in raw_string.split(","):
            if ":" in entry:
                name, limit = entry.split(":")
                users[name.strip()] = int(limit.strip())
    return users

# --- PDF GENERATOR ---
class AestheticReport(FPDF):
    def header(self):
        self.set_fill_color(44, 62, 80)
        self.rect(0, 0, 210, 25, 'F')
        self.set_y(10)
        self.set_font('Arial', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'Eskwela Grading Report', 0, 0, 'C')
        self.ln(25)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by AI - Page {self.page_no()}', 0, 0, 'C')

def create_pdf_report(feedback_text, student_filename):
    pdf = AestheticReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    safe_text = feedback_text.encode('latin-1', 'replace').decode('latin-1')
    lines = safe_text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(2)
            continue
        if line.startswith("# "):
            pdf.ln(5)
            pdf.set_font("Arial", "B", 16)
            pdf.set_text_color(44, 62, 80)
            pdf.cell(0, 10, line.replace("# ", "").upper(), 0, 1, 'L')
            pdf.set_draw_color(200, 200, 200)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(2)
        elif line.startswith("## "):
            pdf.ln(4)
            pdf.set_font("Arial", "B", 13)
            pdf.set_text_color(52, 152, 219)
            pdf.cell(0, 8, line.replace("## ", ""), 0, 1, 'L')
        elif line.startswith("**Q") or line.startswith("Q"):
            pdf.ln(3)
            pdf.set_font("Arial", "B", 11)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, line.replace("*", ""), 0, 1, 'L')
        elif "Status:" in line:
            pdf.set_font("Arial", "B", 10)
            if "Correct" in line: pdf.set_text_color(39, 174, 96)
            elif "Incorrect" in line: pdf.set_text_color(192, 57, 43)
            elif "Partial" in line: pdf.set_text_color(211, 84, 0)
            elif "UNATTEMPTED" in line: pdf.set_text_color(127, 140, 141)
            else: pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, line.replace("*", ""), 0, 1, 'L')
        elif "Score:" in line:
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(44, 62, 80)
            pdf.cell(0, 6, line.replace("*", ""), 0, 1, 'L')
        else:
            pdf.set_font("Arial", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, line.replace("*", ""))
            
    report_filename = f"Report_{student_filename}.pdf"
    pdf.output(report_filename)
    return report_filename

# --- TABS LAYOUT ---
tab1, tab2, tab3 = st.tabs(["Grading Desk", "Tutor History", "Developer Dashboard"])

# ==========================
# TAB 1: GRADING DESK
# ==========================
with tab1:
    col1, col2 = st.columns([1, 2])
    
    # --- GET USERS FROM ENV ---
    authorized_users = get_authorized_users()

    with col1:
        st.subheader("Configuration")
        
        # 1. USER VALIDATION
        tutor_name_input = st.text_input("Tutor Username")
        
        # Check Access
        is_authorized = False
        remaining_balance = 0
        
        if tutor_name_input:
            if tutor_name_input in authorized_users:
                is_authorized = True
                max_limit = authorized_users[tutor_name_input]
                
                # Fetch Usage from DB
                try:
                    current_usage = db_utils.get_tutor_usage(tutor_name_input)
                except:
                    current_usage = 0 # Default if DB fail
                
                remaining_balance = max_limit - current_usage
                usage_percent = min(current_usage / max_limit, 1.0)
                
                # Display Usage Meter
                st.write(f"**Credit Usage:** {current_usage:,} / {max_limit:,} Tokens")
                st.progress(usage_percent)
                
                if current_usage >= max_limit:
                    st.error("❌ Quota Exceeded. Contact Admin.")
                    is_authorized = False # Block access
                elif usage_percent > 0.9:
                    st.warning("⚠️ Low Balance")
                else:
                    st.success("✅ Active Plan")
            else:
                st.error("🚫 User not found in system.")

        uploaded_scheme = st.file_uploader("1. Marking Scheme (PDF)", type=["pdf"])
        
        st.write("**Exam Settings:**")
        max_score_input = st.number_input("Total Marks (0 = Auto-detect)", min_value=0, value=0)
        st.markdown("---")
        use_custom = st.checkbox("Use Custom Template?")
        uploaded_template = None
        if use_custom:
            uploaded_template = st.file_uploader("2. Report Template (PDF)", type=["pdf"])
    
    with col2:
        st.subheader("Student Uploads")
        uploaded_files = st.file_uploader("Drop student PDFs here", accept_multiple_files=True, type=["pdf"])

        # BUTTON LOGIC: Only active if Authorized AND has Files
        if st.button("Run Batch Grading", type="primary", disabled=(not is_authorized)):
            if not is_authorized:
                st.error("You are not authorized to grade.")
            elif not uploaded_files or not uploaded_scheme:
                st.error("Please upload the Marking Scheme and Student Papers.")
            else:
                st.info("Processing... please wait.")
                
                with open("temp_scheme.pdf", "wb") as f:
                    f.write(uploaded_scheme.getbuffer())
                
                template_path = None
                if uploaded_template:
                    with open("temp_template.pdf", "wb") as f:
                        f.write(uploaded_template.getbuffer())
                    template_path = "temp_template.pdf"
                
                progress_bar = st.progress(0)
                
                for i, student_file in enumerate(uploaded_files):
                    with open("temp_student.pdf", "wb") as f:
                        f.write(student_file.getbuffer())
                    
                    try:
                        score, feedback, tokens = grader_engine.grade_submission(
                            "temp_student.pdf", 
                            "temp_scheme.pdf", 
                            template_path,
                            max_score_override=max_score_input
                        )
                        
                        pdf_path = create_pdf_report(feedback, student_file.name)
                        student_url = storage_utils.upload_file(student_file, student_file.name)
                        
                        db_utils.save_grade(tutor_name_input, student_file.name, score, feedback, student_url, tokens)
                        
                        st.success(f"✅ {student_file.name} | Score: {score} | Tokens: {tokens}")
                        
                        with open(pdf_path, "rb") as pdf_file:
                            st.download_button(f"Download Report ({student_file.name})", pdf_file, file_name=pdf_path)
                            
                    except Exception as e:
                        st.error(f"Failed {student_file.name}: {e}")
                    
                    progress_bar.progress((i+1)/len(uploaded_files))

# ==========================
# TAB 2: TUTOR HISTORY
# ==========================
with tab2:
    st.subheader("Grading History")
    search_user = st.text_input("Enter Username to view history:", value=tutor_name_input if tutor_name_input else "")
    
    if search_user:
        try:
            conn = db_utils.get_db_connection()
            df = pd.read_sql(f"SELECT filename, score, tokens_used, timestamp, file_url FROM grading_logs WHERE username='{search_user}' ORDER BY timestamp DESC", conn)
            st.dataframe(df, use_container_width=True)
        except:
            st.warning("No data found.")

# ==========================
# TAB 3: DEVELOPER DASHBOARD
# ==========================
with tab3:
    st.subheader("Developer Settings")
    admin_password = st.text_input("Enter Admin Password", type="password")
    
    if admin_password == os.environ.get("ADMIN_PASS"):
        st.success("Access Granted")
        try:
            conn = db_utils.get_db_connection()
            total_papers = pd.read_sql("SELECT COUNT(*) FROM grading_logs", conn).iloc[0,0]
            total_tokens = pd.read_sql("SELECT SUM(tokens_used) FROM grading_logs", conn).iloc[0,0]
            recent_logs = pd.read_sql("SELECT id, username, filename, tokens_used, timestamp FROM grading_logs ORDER BY timestamp DESC LIMIT 10", conn)
            
            if total_tokens is None: total_tokens = 0
            est_cost = (total_tokens / 1_000_000) * 0.50 
            
            m1, m2, m3 = st.columns(3)
            m1.metric("Total Papers Graded", total_papers)
            m2.metric("Total Tokens Used", f"{total_tokens:,}")
            m3.metric("Est. Cloud Cost", f"${est_cost:.4f}")
            
            st.write("### Global Recent Activity")
            st.dataframe(recent_logs, use_container_width=True)
            
            st.write("### Active Quotas (.env)")
            st.write(get_authorized_users())
            
        except Exception as e:
            st.error(f"Database Error: {e}")
    elif admin_password:
        st.error("Incorrect Password")